name: Testing work flow

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:
      inputs:
        testing1:
          description: 'first test'
          required: true
        testing2:
          description: 'second test'
          required: true
        testing3:
          description: 'third test'
          required: false
    discussion_comment:
      types: created

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: with ENV
              id: with_ENV
              run: |
                echo "random_number=1" >> $GITHUB_OUTPUT
                echo ${{steps.with_ENV.outputs.random_number}}
            - name: without
              id: without
              run: |
                echo "random_number=1"
                echo ${{steps.without.outputs.random_number}}

