name: Testing work flow

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:
      inputs:
        testing1:
          description: 'first test'
          required: true
        testing2:
          description: 'second test'
          required: true
        testing3:
          description: 'third test'
          required: false

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Dump Github Context
              env: 
                GITHUB_CONTEXT: ${{toJSON(github)}}
              run: echo $GITHUB_CONTEXT
            - name: Dump env context
              env:
                ENV_CONTEXT: ${{toJSON(env)}}
              run: echo $ENV_CONTEXT
            - name: Dump vars context
              env:
                VARS_CONTEXT: ${{toJSON(vars)}}
              run: echo $VARS_CONTEXT
              
