name: Testing work flow

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: hi
              run: |
                  echo "::Hello world"
                  exit 0
