name: Testing work flow

on:
    pull_request:
        branches:
            - main
        paths:
            - hi.ts
            - test/**
    workflow_dispatch:
      # inputs:
      #   testing1:
      #     description: 'first test'
      #     required: true
      #   testing2:
      #     description: 'second test'
      #     required: true
      #   testing3:
      #     description: 'third test'
      #     required: false
    discussion_comment:
      types: created

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: run node
              id: with_ENV
              run: node something.js

