name: Testing work flow

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:
      inputs:
        testing1:
          description: 'first test'
          required: true
        testing2:
          description: 'second test'
          required: true
        testing3:
          description: 'third test'
          required: false

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: hi
              run: |
                  echo "::Hello world"
                  exit 0
