name: Testing work flow

on:
  push:
    branches:
      - main

jobs:
  hell:
    runs-on: ubuntu-latest
    steps: 
      - name: hi
        run: |
          echo "::Hello world"
          exit 0
        
