name: Testing work flow

on:
    pull_request:
        branches:
            - main
        paths:
            - hi.ts
            - test/**
    workflow_dispatch:
      # inputs:
      #   testing1:
      #     description: 'first test'
      #     required: true
      #   testing2:
      #     description: 'second test'
      #     required: true
      #   testing3:
      #     description: 'third test'
      #     required: false
    discussion_comment:
      types: created

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: Check out code
            uses: actions/checkout@v2
  
          - name: Run JavaScript
            id: runJS
            run: node something.js

          - name: Return
            run: echo ${{ steps.runJS.outputs.thing }}
          

