name: Main build
run-name: Deploy to Development (Date ${{ github.event.head_commit.timestamp }}) (Version ${{ github.ref_name }})

on:
  push:
    branches:
      - main
    tags:
        - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ESLint
        run: |
          npm run lint:eslint 
          echo "All files pass ESLint checks 🎉"

      - name: Run Jest
        run: npx jest --coverage=false
