name: Teams notification

on:
  workflow_dispatch:

jobs:
  with_emails:
    name: One with emails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: MSTeams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "Overwrote title in test"
