name: Daily Build

on:
  workflow_dispatch:
    inputs:
      eas_build_profile:
        description: "EAS build profile (for adhoc builds)"
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set EAS build profile
        run: echo "EAS_BUILD_PROFILE=${{ github.event.inputs.eas_build_profile || 'test' }}" >> $GITHUB_ENV

      - name: Checkout repository
        run: exit 1

      - name: Run on failure
        if: failure()
        uses: neonidian/teams-notify-build-status@v4.1
        with:
          webhookUrl: >-
            ${{
              (env.EAS_BUILD_PROFILE == 'dev' || env.EAS_BUILD_PROFILE == 'prod') && vars.TEAMS_WEBHOOK_URL ||
              env.EAS_BUILD_PROFILE == 'test' && vars.TEAMS_WEBHOOK_URL2
            }}
          title: ${{ github.workflow }} Failed
          titleBackgroundColor: "failure"
          message: "${{ github.workflow }} Failed: Please check the logs for more details."
        env:
          SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
