name: MS Teams Deploy Card

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: exit 1

      - name: Run on failure
        if: failure()
        uses: neonidian/teams-notify-build-status@v4.1
        with:
          webhookUrl: ${{ secrets.TEAMS_WEBHOOK_URL }}
          status: Failure
          message: "Daily Build Failed at ${{ format(fromJson(steps.current_time.outputs.result).time, 'YYYY-MM-DD HH:mm:ss') }} MYT"
        env:
          SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
