name: MS Teams Deploy Card

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: neonidian/teams-notify-build-status@v4.1
        with:
          webhookUrl: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: Tests
          titleBackgroundColor: "failure"
          message: Unit tests have been run for version
