name: MS Teams Deploy Card

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: exit 1

      - name: Run on failure
        if: failure()
        uses: neonidian/teams-notify-build-status@v4.1
        with:
          webhookUrl: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "Daily Build Failed: ${{ github.job }}"
          titleBackgroundColor: "failure"
          status: Failure
          message: "Daily Build Failed in job: ${{ github.job }}. Additional details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
